#!@bash@/bin/bash

parent=$(ps -o comm= $PPID)
username="hnefatl@gmail.com"

while ! @lastpass_cli@/bin/lpass status --quiet ; do
    @dunst@/bin/dunstify -A "Authenticate,$TERMINAL -e \"bash -c 'i3-msg floating enable>/dev/null ; lpass login $username'\"" -u normal "'$parent' running command '$*', requires authentication." >/dev/null
done

eval "$@"